### ISSUE TITLE
Undefined array key "post_ID"

### ISSUE THREAD

**Issue by ronakkaria01** [sirv/wordpress#1]
Undefined array key "post_ID" at line 368 in plugdata/includes/classes/woo.class.php

$product_id = $post_type == 'product' ? $_POST['post_ID'] : $product_id;

Error occurs in the roots.io/radicle project while creating any new page/post type

post-new.php?post_type=page

**NOTE - I am not able to create a new post for any and all post types**

**Comment by mbilykov** [comment]
> Undefined array key "post_ID" at line 368 in plugdata/includes/classes/woo.class.php
> 
> $product_id = $post_type == 'product' ? $_POST['post_ID'] : $product_id;
> 
> Error occurs in the roots.io/radicle project while creating any new page/post type
> 
> post-new.php?post_type=page
> 
> **NOTE - I am not able to create a new post for any and all post types**

Hi ronakkaria01,

This issue was potentially fixed in version 7.2.8. Pls try new version.

**Comment by ronakkaria01** [comment]
Hi Misha,

I'm trying to install the plugin via composer from wpackagist-plugin/sirv

I still see 7.2.7 as the latest version.
Best Regards
Ronak - 01242 511912

On 12 Jul 2024, at 1:44 PM, MishaBelikov ***@***.***> wrote:



Undefined array key "post_ID" at line 368 in plugdata/includes/classes/woo.class.php

$product_id = $post_type == 'product' ? $_POST['post_ID'] : $product_id;

Error occurs in the roots.io/radicle project while creating any new page/post type

post-new.php?post_type=page

NOTE - I am not able to create a new post for any and all post types

Hi ronakkaria01,

This issue was potentially fixed in version 7.2.8. Pls try new version.

**Comment by mbilykov** [comment]
> I'm trying to install the plugin via composer from wpackagist-plugin/sirv I still see 7.2.7 as the latest version.

Hi Ronak,

Try to update you composer.json with new sirv record:
`"wpackagist-plugin/sirv":"7.2.8"`

Please let me know if issue is fixed or not.
